name: "Run CI"

on: pull_request

jobs:
  pre-commit:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1

  cppcheck:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: prefix-dev/setup-pixi@v0.4.1
        with:
          pixi-version: v0.9.1
          cache: true

      - name: cppcheck installation
        run: pixi add cppcheck
      - name: Configure
        run:  |
          cmake -S . -B .build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXAMPLES=ON
          cppcheck --enable=all -q --project=.build/compile_commands.json --suppressions-list=.cppcheck 2> cppcheck_err.txt
        shell: pixi run bash {0}
      - name: Check for errors
        run: |
          if [[ -s cppcheck_err.txt ]];
          then
            cat cppcheck_err.txt
            exit -1
          fi

  init:
    runs-on: macos-latest
    needs: [pre-commit, cppcheck]
    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.5.1

        with:
          pixi-version: v0.16.1
          cache: true
      - run: pixi run test
